### ISSUE TITLE
maxEntries setting in config seems not to work

### ISSUE THREAD

**Issue by detto65** [qistoph/MMM-nstreinen#22]
default is 5, any other number does not work

**Comment by detto65** [comment]
MM only shows me 2-3 entries, max 1 hr in advance.
The API also returns only 3 at the moment, while the "maxjourneys" was set as 25.
(5 entries did work yesterday)

**Comment by qistoph** [comment]
The NS API doesn't always return the maximum request number of items. Especially on less busy stations, the lists might be shorter.

You could set `fade: false`, to at least show the bottom items more clearly.

There also was a bug where the configured maxEntries was not properly send with in the API request. This is fixed in the current master branch.
