### ISSUE TITLE
"Dit reisadvies vervalt" not shown on mirror

### ISSUE THREAD

**Issue by Lukelumia** [qistoph/MMM-nstreinen#9]
The problem i'm having, and probably all other users of the MM-NStreinenn module, is the missing message of "dit reisadvies vervalt" or roughly translated: "This travel advice is not longer valid".

### Mobile version:
![Mobile version](https://i.imgur.com/4eWUnlr.png)

### MagicMirror version
![MagicMirror version](https://i.imgur.com/e4NKqYs.jpg)

## How to test for yourself
What i did to show this problem:
1. Look at the NS app to see where the problems are this day
2. Travel from this station to another
3. If the options are grayed out in the app, try it on your mirror
4. The mirror will show the trains are driving as normal (Not good)

## What should the MagicMirror show
The mirror should show the train is not driving at all (preferably), this can be shown with a cross<img src="http://wiki.augmensys.com/images/1/12/IC_Cross_Mark.png" alt="Cross" width="30"/> or/and by ~~Strikethrough text~~.

The "Let op, storing" message can be shown with a explanation mark or similar.

**Comment by qistoph** [comment]
The trip planner was missing code to handle this kind of situations. Updated with e069853069e4a0ac1da1a19250c1209e6b8ede22.

It's a little hard to test, because we need actual trouble to see if it's working. I'm closing the issue for now. Feel free to re-open if you're experiencing issues with this update.
